# Generated by Django 5.2.8 on 2025-11-26 13:44

from django.db import migrations


class Migration(migrations.Migration):
    """
    このマイグレーションは、Categoryモデルのモデルオプション (Metaクラスの内容) のみを変更します。
    具体的には、管理画面での表示名を変更します。
    """

    # このマイグレーションが依存するマイグレーションを指定
    dependencies = [
        # 0002_alter_task_options_alter_category_name の後に実行される
        ("tasks", "0002_alter_task_options_alter_category_name"),
    ]

    # データベースに対して実行される操作のリスト
    operations = [
        # Category モデルのオプション変更
        migrations.AlterModelOptions(
            name="category",
            # 'verbose_name_plural' (複数形での表示名) を 'Categories' に設定
            # 📝 Note: 日本語環境での表示名を設定するために、models.pyでさらに変更されている可能性があります。
            options={"verbose_name_plural": "Categories"},
        ),
    ]
