# Generated by Django 5.2.8 on 2025-11-28 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    このマイグレーションは、Categoryモデルにユニーク制約を追加し、
    Taskモデルのフィールドに日本語の表示名 (verbose_name) を設定します。
    """
    
    # このマイグレーションが依存するマイグレーションを指定
    dependencies = [
        # 0003 の後に実行される
        ('tasks', '0003_alter_category_options'),
        # ユーザーモデルに依存
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # データベースに対して実行される操作のリスト
    operations = [
        # 1. Category モデルのオプション変更
        migrations.AlterModelOptions(
            name='category',
            # 'verbose_name_plural' (複数形での表示名) を 'カテゴリ' に設定
            options={'verbose_name_plural': 'カテゴリ'},
        ),
        
        # 2. Task モデルの 'category' フィールド変更 (日本語表示名を追加)
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.category', verbose_name='カテゴリ'),
        ),
        
        # 3. Task モデルの 'description' フィールド変更 (日本語表示名を追加)
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='詳細'),
        ),
        
        # 4. Task モデルの 'due_date' フィールド変更 (日本語表示名を追加)
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='期限'),
        ),
        
        # 5. Task モデルの 'status' フィールド変更 (日本語表示名を追加)
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, '未着手'), (1, '進行中'), (2, '完了')], default=0, verbose_name='進捗状況'),
        ),
        
        # 6. Task モデルの 'title' フィールド変更 (日本語表示名を追加)
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, verbose_name='タイトル'),
        ),
        
        # 7. Category モデルにユニーク制約を追加
        migrations.AlterUniqueTogether(
            name='category',
            # userとnameの組み合わせがデータベース全体でユニークであることを保証
            unique_together={('user', 'name')},
        ),
    ]