# Generated by Django 5.2.8 on 2025-11-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    このマイグレーションは、Taskモデルの 'priority' フィールドの選択肢とデフォルト値を変更します。
    具体的には、'none'（なし）オプションを追加し、デフォルト値を 'none' に設定します。
    """

    # このマイグレーションが依存するマイグレーションを指定
    dependencies = [
        # 0005 の後に実行される
        ('tasks', '0005_task_priority'),
    ]

    # データベースに対して実行される操作のリスト
    operations = [
        # 1. Task モデルの 'priority' フィールドを変更
        migrations.AlterField(
            model_name='task',
            name='priority',
            # 選択肢リストに ('none', 'なし') を追加し、デフォルト値を 'none' に変更
            field=models.CharField(
                choices=[('none', 'なし'), ('low', '低'), ('medium', '中'), ('high', '高')], # 新しい優先度の選択肢
                default='none', # デフォルト値を 'none' に設定
                max_length=10, 
                verbose_name='優先度' 
            ),
        ),
    ]